-- Create the projects table
CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT,
    tags TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Create policies
-- Policy: Everyone can view projects
CREATE POLICY "Public profiles are viewable by everyone" 
ON projects FOR SELECT 
USING (true);

-- Policy: Only authenticated users (admins ideally, but for now any auth user with key) can insert/update/delete
-- Note: In a real production app, checking for specific 'admin' role in metadata is better.
-- For this "Admin Mode" simulation where admin is just a client-side key protection + auth:
-- We will allow authenticated users to modify. 
-- The client-side app protects the "Edit" UI with the specific Admin Key.

CREATE POLICY "Authenticated users can insert projects" 
ON projects FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update projects" 
ON projects FOR UPDATE 
USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete projects" 
ON projects FOR DELETE 
USING (auth.role() = 'authenticated');

-- Insert initial dummy data
INSERT INTO projects (title, description, image_url, tags)
VALUES 
(
    'Análisis de Integridad Estructural', 
    'Implementación de algoritmos avanzados para el cálculo de resistencia de materiales en infraestructuras críticas.', 
    'https://raw.githubusercontent.com/marcosdespujoscelular-hash/despux/main/img1/PROY.png',
    ARRAY['Python', 'AutoCAD API', 'Node.js', 'TensorFlow']
),
(
    'Ciclón Separador Inoxidable', 
    'Diseño y fabricación de un sistema de separación ciclónica en acero inoxidable para ambientes corrosivos.', 
    'https://raw.githubusercontent.com/marcosdespujoscelular-hash/despux/main/img1/ciclon.png',
    ARRAY['SolidWorks', 'CFD Simulation', 'Inox 304L']
);
